---
subtitle: "Pollinator guild for a small strip of *Solidago* on WCU campus"
author: "J. Ted Hillert"
date: "`r Sys.Date()`"

output:
  bookdown::word_document2:
    toc: no
    number_sections: FALSE
    always_allow_html: yes
    
bibliography:
- aRticles.bib
- R-packages.bib

csl: ecology.csl

---

```{r setup, include=FALSE}


knitr::opts_chunk$set(echo = FALSE)

library(broom)
library(car)
library(emmeans)
library(ggfortify)
library(kableExtra)
library(latex2exp)
library(multcomp)
library(patchwork)
library(tidyverse)

papaja::r_refs(file = "paper.bib")

options(scipen = 99) # a "trick" to keep R from using scientific notation.

options(knitr.kable.NA = "")


```


## Abstract


## Introduction


## Methods


## Results

```{r import, include=FALSE}
data<-read_csv("data.csv")

data

data$polltype<-factor(data$polltype, 
                   levels = c('honbee', 
                              'bucabee',
                              'wasp',
                              'smbee',
                              'beetle',
                              'lbutterfly',
                              'sbutterfly',
                              'flies',
                              'ant'
                              ),
                   labels = c('Honeybee',
                              'Carpenter and Bumblebee',
                              'Wasp',
                              'Small Bee',
                              'Beetle',
                              'Large Butterfly',
                              'Small Butterfly',
                              'Flies',
                              'Ant'
                              )
                   )

```

```{r scatter, eval=FALSE, include=FALSE}
#| fig.cap = "Scatterplot of male longevity versus thorax length."

ggplot(data) +
  geom_histogram(aes(polltype,visits)) +
  ylab("Number of Visits") +
  xlab("Pollinator Type") +
  theme_classic()

 ```

```{r mod1, include=FALSE}
#| fig.show = 'hide'

mod1<-lm(visits~polltype+
           replicates+
           polltype:replicates,
        data
        )

mod1

autoplot(mod1)

mod1tab<-Anova(mod1)

mod1tab

```

```{r mod1tab, echo=FALSE}
#| fig.show = 'hide'
mod1tab$`Pr(>F)` <- format.pval(mod1tab$`Pr(>F)`,
                                 eps = 0.0001,
                                 digits = 4,
                                 na.form = ""
                                 )

kbl(mod1tab, 
    digits = c(3, 0, 3, 4), 
    caption = "Test for homogeneity of slopes.",
    align = "r"
    ) |>
    kable_classic(full = FALSE)
    

```

```{r modplot, echo=FALSE}
#| fig.cap=""

data$pred<-predict(mod1)

plot<- ggplot(data) +
  geom_point(aes(x = polltype, 
                 y = visits, 
                 group = polltype, 
                 color = polltype,
                 shape = polltype)
             ) +
#  geom_line(aes(x = polltype, 
#                y = pred, 
#                group = polltype, 
#                linetype = polltype, 
#                color = polltype)
#            ) +
  scale_y_continuous(
    name = 'Number of Flower Visits'
  )+
  scale_x_discrete(
    name = 'Pollinator Type'
    ) +
  scale_shape_discrete(name = 'Females') +
  scale_color_discrete(name = 'Females') +
  scale_linetype_discrete(name = 'Females') +
  theme_classic(base_size = 10) +
  theme(legend.position = "none")

plot

```

## Discussion


## Conclusion


\newpage


# References






















